package it.polimi.awt.images.converter;

import it.polimi.awt.images.ImageProvider;
import it.polimi.awt.images.entity.Image;
import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;

import java.util.ArrayList;
import java.util.List;

public class JSONConverter {

    public List<Image> convertJSON(String jsonResponse, ImageProvider provider) throws JSONException {
        JSONObject jsonObject = new JSONObject(jsonResponse);
        JSONObject parent = jsonObject.getJSONObject("photos");
        JSONArray jsonArray = parent.getJSONArray("photo");

        List<Image> imageList = new ArrayList<>();

        // Iterate through all the images and extract metadata
        for (int i = 0; i < jsonArray.length(); i++) {
            JSONObject imageMetadata = jsonArray.getJSONObject(i);
            String id = imageMetadata.getString("id"); // ID generated by flickr
            String title = imageMetadata.getString("title"); // Image/photo title
            String secret = imageMetadata.getString("secret"); // Secret id of the image/photo
            String server = imageMetadata.getString("server"); // Server where image is stored
            int farm = imageMetadata.getInt("farm"); // Farm where image is aggregated
            double longitude = imageMetadata.getDouble("longitude"); // Geo parameter longitude
            double latitude = imageMetadata.getDouble("latitude"); // Geo parameter latitude

            Image image = new Image(id, title, secret, server, provider, farm, longitude, latitude);
            imageList.add(image);
        }
        return imageList;
    }
}
